apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drew-enforce-webhook-cert
  namespace: learning
spec:
  commonName: 'drew-enforce-webhook.learning.svc'
  dnsNames:
    - 'drew-enforce-webhook.learning.svc'
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  secretName: drew-enforce-webhook-cert