apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "drew-enforce-webhook"
webhooks:
  - name: "drew-enforce-webhook.YOUR_DOMAIN"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: learning
        name: drew-enforce-webhook
        path: /validate-pods
        port: 443
      caBundle: "" # Results of `kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'`
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2