---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: CSR_NAME
spec:
  groups:
    - system:authenticated
  request: REQUEST
  signerName: kubernetes.io/kubelet-serving
  usages:
    - digital signature
    - key encipherment
    - server auth
