apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor
  namespace: learning
  annotations:
    container.apparmor.security.beta.kubernetes.io/hello: localhost/k8s-apparmor-example-allow-write
spec:
  containers:
    - name: hello
      image: busybox:1.36
      command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]