---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
  namespace: learning
spec:
  storageClassName: longhorn
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
