---
apiVersion: v1
kind: Pod
metadata:
  name: sec-context
  namespace: learning
spec:
  volumes:
    - name: sec-ctx
      emptyDir: {}
  containers:
    - name: security-demo
      image: busybox:1.36.1
      command:
        - sh
        - -c
        - sleep 1h
      volumeMounts:
        - mountPath: /data/demo
          name: sec-ctx
      securityContext:
        readOnlyRootFilesystem: true