apiVersion: v1
kind: ConfigMap
metadata:
  name: web-conf
  namespace: learning
data:
  default: |
    server {
      listen 80 default_server;
      server_name _;
      root /usr/share/nginx/html;
      index index.html index.html;
    }
  metrics: |
    server {
      listen 8080;
      server_name _;
      location /stub_status {
        stub_status on;
      }
    }