---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-more
  namespace: learning
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: learning
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-more-binding
  namespace: learning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-more
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ada
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: learning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: learning
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: learners